### PR TITLE
workspace: add tooltipDelay and theme

### PR DESCRIPTION
**Pull request by ghost**
Also fixed a minor typo in the README. Example:
```nix
programs.plasma = {
  enable = true;

  workspace = {
    clickItemTo = "select";
    tooltipDelay = 5;
    theme = "breeze-dark";
  };
};

### CODE REVIEW

**Comment by toast003** [comment]
Looks good!
Thanks for the pr @ProminentRetail ^^

**Comment by drupol** [comment]
Hello,

This commit broke my upgrade.

I don't have a theme set, therefore I get the error:

```
       … while evaluating the option `home-manager.users.pol.programs.plasma.workspace.theme':

       error: A definition for option `home-manager.users.pol.programs.plasma.workspace.theme' is not of type `string'. Definition values:
       - In `/nix/store/lzmagadaigrcmqc2ccsinvlcimda7s57-source/modules/workspace.nix': null
```

When I set the theme manually, I get:

```
       error: The option `home-manager.users.pol.programs.plasma.theme' does not exist. Definition values:
       - In `/nix/store/fsvs8mc46aylssf2jhfi13xjc4m1pci4-source/hosts/common/kdeplasma.nix': "breeze-dark"
```

**Comment by toast003** [comment]
@drupol I'm working on it rn, my bad for not testing the pr with `workspace.theme` unset

Btw when you set the theme manually you set `theme`, not `workspace.theme`. Set it to that while I try to figure out what's going wrong

**Comment by drupol** [comment]
Indeed, fixed now. I linked my commit to this issue if you're curious to see my profile.

**Comment by toast003** [comment]
@drupol can you try https://github.com/pjones/plasma-manager/pull/30 ?

I have tested and it works with `theme` unset, but just to be sure

**Comment by drupol** [comment]
Just tested with your repo and branch and I got no more issue when building it. However, what's the behaviour of KDE when setting a theme to a null value?

**Comment by toast003** [comment]
I don't know ¯\\\_(ツ)_/¯
[This line](
https://github.com/pjones/plasma-manager/blob/fd6349f6757da2641aa164697a63eac17147cc6b/modules/workspace.nix#L47C11-L47C11) doesn't set any theme unless `programs.plasma.enable` is enabled AND `programs.plasma.workspace.theme` is not null, and since null is the default it just doesn't do anything

**Comment by drupol** [comment]
all good then, :+1:

**Pull request merged**
