### PR TITLE
Add more powerdevil options for laptops

### PR DESCRIPTION
**Pull request by ribru17**
Ports some additional options over to the powerdevil settings, such as hibernation support, low battery configuration options, and events to trigger when closing the laptop lid.

### CODE REVIEW

**Review by HeitorAugustoLN — APPROVED** [review]
Looks good to me!

**Comment by magnouvean** [comment]
Nice, looks good to me as well. Has there been some quick test to check that the settings actually do apply when logging out/in again (I can't check cause I don't have a laptop available)? If so I'm happy to merge!

**Comment by ribru17** [comment]
Thanks for reviewing! Yes I ran a (very) quick test by changing my personal plasma-manager flake input to my local branch and from what I can see the new values are indeed written to the powerdevilrc config file :+1:

**Comment by ribru17** [comment]
As for logging out and back in, I will check now.  Give me one moment

**Comment by ribru17** [comment]
I can confirm that the values remain in the config file, and the GUI settings panel recognizes them properly :+1:

**Comment by magnouvean** [comment]
Great I'll merge soon, thanks for the contributions :)

**Pull request merged**
