### PR TITLE
Add widget-specific options for Kickoff

### PR DESCRIPTION
**Pull request by HeitorAugustoLN**
Did not put some options such as: `favoritesPortedToKAstats`, `systemApplications`, `systemFavorites`. As probably it is not needed to be set. And there is not enough documentation on these options. Maybe i will look into it in the future, and maybe add it

### CODE REVIEW

**Comment by HeitorAugustoLN** [comment]
Tested, it is working fine.

**Comment by HeitorAugustoLN** [comment]
Only the `favorites` option doesn't work. The option is doing the job. And I don't even think it is our fault in the scripting. It never worked for me.

image
Sets everything fine. But the favorites doesn't update

image

**Comment by magnouvean** [comment]
I'll try to get the favorites working myself (maybe it needs a restart of `plasma-plasmadesktop` maybe, or some other weird trick). If that doesn't work I think it would be better to drop it for now as having an option which doesn't work doesn't really make sense, even if the bug is on plasma desktop-scripts and not in `plasma-manager`.

It might take a couple days before I can check it out though.

**Comment by HeitorAugustoLN** [comment]
I would say the bug is in plasma-desktop scripts. But if you can get it working, it would be nice. But if not, i will remove it from the options

**Comment by magnouvean** [comment]
Yeah I don't know what's happening with the favorites either. We can find out at a later time. I reckon we just remove that and I can merge. Everything else looks fine.

**Comment by HeitorAugustoLN** [comment]
> Yeah I don't know what's happening with the favorites either. We can find out at a later time. I reckon we just remove that and I can merge. Everything else looks fine.

Removed.

**Pull request merged**
