### PR TITLE
fix example

### PR DESCRIPTION
**Pull request by Asqiir**
This is a fix for the errors noticed by @dvaerum in #84.

I had to update the stateversion (18.09 would have been default, but it did not compile with the old version but does with the new).

The example now works again.

### CODE REVIEW

**Comment by Asqiir** [comment]
This should also close #57.

**Comment by Asqiir** [comment]
@magnouvean I hope it's ok to ping you (or should I just wait with PRs like that?)

**Comment by magnouvean** [comment]
Yeah no problem about it. I have been reworking the documentation and examples a bit in my fork at https://github.com/magnouvean/plasma-manager/tree/documentation-updates, and among the changes have been in flake.nix. There I've rewritten the flake.nix quite a lot. I think it should be ready in a few days and we do one big pr for improved documentation. Therefore I think there's not much point in fixing this right now as it probably will just be changed in a couple days anyway. I'll open a draft pr right away and we can work there directly

**Comment by Asqiir** [comment]
Closing this in favour of #104

**Pull request closed without merging**
