### PR TITLE
Add NightLight options to kwin modules

### PR DESCRIPTION
**Pull request by HeitorAugustoLN**

### CODE REVIEW

**Comment by HeitorAugustoLN** [comment]
It wasn't supposed to have so many commits, but now it is fine.

**Comment by HeitorAugustoLN** [comment]
I had some trouble with assertions, so I force-pushed a little bit to clean up the commit history.

**Comment by magnouvean** [comment]
This looks good. I'll check this out tomorrow together with the other prs and merge quickly hopefully :)

**Comment by magnouvean** [comment]
Works great!

**Pull request merged**
