### PR TITLE
Add settings option for all widget-specific options

### PR DESCRIPTION
**Pull request by HeitorAugustoLN**
Could be useful for users that want to configure options that are not covered by the widget-specific options, but don't want to configure the entire widget manually.

### CODE REVIEW

**Comment by HeitorAugustoLN** [comment]
I just now saw that I didn't put the right example for application-title-bar

**Review by magnouvean — COMMENTED** [review]
I see that the use of `//` for adding the `extraConfig` configuration to the widget causes some problems. For example:
```nix
        plasmusicToolbar = {
          preferredSource = "any";
          panelIcon.albumCover = {
            useAsIcon = true;
            radius = 2;
          };
          showPlaybackControls = false;
          extraConfig = {
            General.somesetting = 4;
          };
        };
```
Will result in only `somesetting` key is set in the`General` group for the widget configuration (so most of the configuration is simply ignored). This is due to for example:
```nix
{
  General = { key1 = 1; key2 = 2; }
} // { General.key3 = 3; }
```
Will evaluate to `{General.key3 = 3;}` since `General` exists in both the attrsets and thus only the latter will be used.
I believe `lib.mkMerge` will fix this, but it would be less pretty code (but maybe that's just needed here).

**Comment by ada4a** [comment]
@magnouvean
> `lib.mkMerge`

wouldn't [`lib.recursiveUpdate`](https://ryantm.github.io/nixpkgs/functions/library/attrsets/#function-library-lib.attrsets.recursiveUpdate) be more suitable here?

@HeitorAugustoLN 
this PR seems similar to the pattern that [RFC 42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md) proposes. Do you think it would make sense to bring it closer to that by using `settings` instead of `extraConfig`?

**Comment by magnouvean** [comment]
Yeah I agree with both of the above suggestions (`settings` and `recursiveUpdate`)

**Comment by HeitorAugustoLN** [comment]
Can anybody test the systemmonitor with lib.recursiveUpdate? I don't know if I did it the right way.

**Comment by magnouvean** [comment]
I believe the semicolon should still be there, but you were missing a `)`. We'll see with the CI though

**Comment by HeitorAugustoLN** [comment]
Yeah, i noticed it now.

**Comment by magnouvean** [comment]
The `systemMonitor` widget now seems to work fine, though there still are inifiniteRecursion for the others. I tested a panel with only `systemMonitor` and it works as expected.

**Comment by HeitorAugustoLN** [comment]
plasmusic seems fine too

**Comment by HeitorAugustoLN** [comment]
It seems like the problem is system-tray

**Comment by HeitorAugustoLN** [comment]
I will fix it.

**Comment by HeitorAugustoLN** [comment]
Apparently now it works.

**Comment by magnouvean** [comment]
Seems to work well now, and the code looks good as well. Thanks for this and the other PRs :)

**Comment by HeitorAugustoLN** [comment]
Happy to help :)

**Pull request merged**
