### PR TITLE
modules(fonts): init

### PR DESCRIPTION
**Pull request by pluiedev**
This PR adds a new module for setting system fonts. I honestly spent way too much time reading how `QFont` works, but this module should at least be _very_ comprehensive to anyone who needs it.

Tested locally in my own system flake — works great!

I'm not exactly happy with how I handled the `pointSize` vs `pixelSize` thing, but submodules unfortunately can't have assertions... :(

### CODE REVIEW

**Comment by magnouvean** [comment]
Wow nice work, looks good from what I can tell (although I won't even pretend to understand what half those values mean). We should add a note in the README that font-configuration is supported and maybe represent this module a bit in the examples as well. I'll test some of this as well, but may take a few days (though if you have tested this and it works the amount of testing probably doesn't need to be that much).

**Comment by pluiedev** [comment]
> Wow nice work, looks good from what I can tell (although I won't even pretend to understand what half those values mean). We should add a note in the README that font-configuration is supported and maybe represent this module a bit in the examples as well. I'll test some of this as well, but may take a few days (though if you have tested this and it works the amount of testing probably doesn't need to be that much).

Yeah, realistically *most* people won't EVER have to touch any of these values — my own config only uses the font family and point size, which are the two only required ones anyway. Testing this is actually super easy with the `fontToString` function in place, and maybe we can just move it to a library module along with the ginormous amounts of internal tables and such and refer to it elsewhere xD

**Comment by magnouvean** [comment]
Just tested and everything works perfectly on my end as well. I pushed a very simple example config in the example `home.nix` as it was missing. I see the check fails with this but this isn't the fault of this PR and will be fixed once we make some adjustments to the CI. Are you happy enough with the state of this PR that we can merge now @pluiedev?

**Comment by pluiedev** [comment]
> Just tested and everything works perfectly on my end as well. I pushed a very simple example config in the example `home.nix` as it was missing. I see the check fails with this but this isn't the fault of this PR and will be fixed once we make some adjustments to the CI. Are you happy enough with the state of this PR that we can merge now @pluiedev?

I think so yeah :shipit:

**Pull request merged**
