### PR TITLE
feat(elisa): init Elisa module

### PR DESCRIPTION
**Pull request by SigmaSquadron**
Elisa is the KDE Music Player. It has very few options compared to most KDE apps, but can still be configured relatively easily.

### CODE REVIEW

**Comment by HeitorAugustoLN** [comment]
This is looking pretty good, I will make some edits after I finish my neovim configuration and then I'll merge it :)

**Comment by SigmaSquadron** [comment]
note to self: don't do *that*

**Review by HeitorAugustoLN — APPROVED** [review]
LGTM! Sorry for the big delay. I'll merge right away.

**Comment by SigmaSquadron** [comment]
Formatted and removed the `with lib.strings;`, as it makes the scope unclear.

**Comment by HeitorAugustoLN** [comment]
> Formatted and removed the `with lib.strings;`, as it makes the scope unclear.

In that case it is not a problem, since this adds the `lib.strings` scope only to the function, so it is easier to understand, where these functions come from, but I don't mind it

**Review by HeitorAugustoLN — APPROVED** [review]

**Pull request merged**
